import { getIndexableProjectCount, getMaxProjectTimestamp } from '@/lib/db';
import { absoluteUrl } from '@/lib/seo';
import { SITEMAP_CHUNK } from '../sitemap';

// Sitemap index pointing at the chunked sitemaps generated by sitemap.ts
// (/sitemap/0.xml = static + category/country pages; /sitemap/1..N.xml =
// project detail pages). Referenced from robots.txt.
export const dynamic = 'force-dynamic';

export async function GET() {
  let projectChunks = 0;
  try {
    projectChunks = Math.ceil(getIndexableProjectCount() / SITEMAP_CHUNK);
  } catch {
    projectChunks = 0;
  }

  let lastmod = new Date().toISOString();
  try {
    const ts = getMaxProjectTimestamp();
    if (ts) lastmod = new Date(ts * 1000).toISOString();
  } catch {}

  const ids = Array.from({ length: projectChunks + 1 }, (_, i) => i);
  const body =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    ids
      .map(
        (i) =>
          `  <sitemap><loc>${absoluteUrl(`/sitemap/${i}.xml`)}</loc><lastmod>${lastmod}</lastmod></sitemap>`,
      )
      .join('\n') +
    '\n</sitemapindex>\n';

  return new Response(body, {
    headers: { 'Content-Type': 'application/xml; charset=utf-8' },
  });
}
